# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      release-name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Test Placeholder'
        # Default value if no value is explicitly provided
        default: 'Default Value'
        # Input has to be provided for the workflow to run
        required: false
        # The data type of the input
        type: string

jobs:
  release:
    runs-on: windows-2019

    steps:
      - name: Check out main branch on git repo
        uses: actions/checkout@v1

      - name: Install Node.js and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 13

      - name: npm install
        run: |
          npm install

      - name: run packaging
        run: |
          npm run package-ci