# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      release-name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Test Placeholder'
        # Default value if no value is explicitly provided
        default: 'Default Value'
        # Input has to be provided for the workflow to run
        required: false
        # The data type of the input
        type: string

jobs:
  release:
    runs-on: windows-2025

    steps:      
      - name: Check out testing branch on git repo
        uses: actions/checkout@v1
        with:
          ref: workflow-testing

      - name: _DISCORD compile discord helper child application_ Setup and Install dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Compile C# application
        run: |
          cd dotnet_discord_rpc
          dotnet build
          tree /f

      - name: show directory of built C# program
        run: |
          cd dotnet_discord_rpc/bin/debug/net8.0
          tree /f

      - name: _MAIN compile main application_ Install Nodejs and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 20.13.1

      - name: npm install
        run: |
          npm install

      - name: run packaging
        run: |
          npm run package

      - name: show directory of built Main program
        run: |
          cd release/build/win-unpacked
          tree /f




        



